<?php
  return[
    'minjs'=>[
       'source'=>[
          '/assets/css/animate.css',
          '//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css',
          '/assets/css/font-awesome.min.css',
          '/assets/css/fontello.css',
          '/assets/css/jquery-ui.css',
          '/assets/css/lnr-icon.css',
          '/assets/css/owl.carousel.css',
          '/assets/css/slick.css',
          '/assets/css/trumbowyg.min.css',
          '/assets/css/bootstrap/bootstrap.min.css',
          '//cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/css/fileinput.min.css',
          '/assets/cropperjs/dist/cropper.min.css',
          '//cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css',
          '//cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css',
          '/assets/style.css',
          '/assets/main.css'
       ],
       'desc'=>'/dist/main.js'
    ],
    'mincss'=>[
       'source'=>[
            '//cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/js/plugins/piexif.min.js',
            '//cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/js/plugins/sortable.min.js',
            '/assets/js/vendor/jquery/popper.min.js',
            '/assets/js/vendor/jquery/uikit.min.js',
            '/assets/js/vendor/bootstrap.min.js',
            '//cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/js/fileinput.min.js',
            '//cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/5.0.9/js/locales/pt-BR.js',
            '//cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js',
            '/assets/js/vendor/grid.min.js',
            '/assets/js/vendor/jquery-ui.min.js',
            '/assets/js/vendor/jquery.barrating.min.js',
            '/assets/js/vendor/jquery.countdown.min.js',
            '/assets/js/vendor/jquery.counterup.min.js',
            '/assets/js/vendor/jquery.easing1.3.js',
            '/assets/js/vendor/owl.carousel.min.js',
            '/assets/js/vendor/slick.min.js',
            '/assets/js/vendor/tether.min.js',
            '/assets/js/vendor/trumbowyg.min.js',
            '/assets/js/vendor/waypoints.min.js',
            '/assets/cropperjs/dist/cropper.min.js',
            '/assets/js/crop.js?v='.date('Ymdhis'),
            '/assets/js/main.js'
       ],
       'desc'=>'/dist/default.css'
    ],
    
  ];
?>